force-app/main/default/objects/Session_Booth__c/Session_Booth__c.object-meta.xml
<CustomObject>
    <label>Session/Booth</label>
    <nameField>
        <label>Session/Booth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions/Booths</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Booth__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Booth__c/fields/Trailblazer_Event__c.field-meta.xml
<CustomField>
    <fullName>Trailblazer_Event__c</fullName>
    <label>Trailblazer Event</label>
    <referenceTo>Trailblazer_Event__c</referenceTo>
    <relationshipName>Sessions_Booths</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trailblazer_Event__c/Trailblazer_Event__c.object-meta.xml
<CustomObject>
    <label>Trailblazer Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazer Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SessionBoothTriggerHandler.cls
public without sharing class SessionBoothTriggerHandler {
    public static void generateRandomUniqueCode(
        List<Session_Booth__c> sessionBooths
    ) {
        Set<Id> eventIds = new Set<Id>();
        for (Session_Booth__c sb : sessionBooths) {
            eventIds.add(sb.Trailblazer_Event__c);
        }

        List<Session_Booth__c> existingBooths = [
            SELECT Id, Code__c, Trailblazer_Event__c
            FROM Session_Booth__c
            WHERE Trailblazer_Event__c IN :eventIds
            LIMIT 50000
        ];

        Map<Id, List<String>> existingStrings = new Map<Id, List<String>>();
        for (Session_Booth__c sb : existingBooths) {
            List<String> tmpStrings = new List<String>();
            if (existingStrings.get(sb.Trailblazer_Event__c) != null) {
                tmpStrings = existingStrings.get(sb.Trailblazer_Event__c);
            }
            tmpStrings.add(sb.Code__c);
            existingStrings.put(sb.Trailblazer_Event__c, tmpStrings);
        }

        List<String> generatedRandomStrings = new List<String>();

        for (Session_Booth__c sb : sessionBooths) {
            List<String> existingCodes = new List<String>();
            if (existingStrings.get(sb.Trailblazer_Event__c) != null) {
                existingCodes = existingStrings.get(sb.Trailblazer_Event__c);
            }
            String tmpRandom;
            do {
                tmpRandom = EventAppCtrl.randomString();
            } while (
                existingCodes.contains(tmpRandom) ||
                generatedRandomStrings.contains(tmpRandom)
            );

            sb.Code__c = tmpRandom;
            generatedRandomStrings.add(tmpRandom);
        }
    }
}