force-app/main/default/objects/Event_Activity__c/Event_Activity__c.object-meta.xml
<CustomObject>
    <label>Event Activity</label>
    <nameField>
        <displayFormat>EVA-{0000}</displayFormat>
        <label>Event Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Activity__c/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <label>Additional Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Activity__c/fields/Event_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Event_Attendee__c</fullName>
    <label>Event Attendee</label>
    <referenceTo>Event_Attendees__c</referenceTo>
    <relationshipLabel>Event Activities</relationshipLabel>
    <relationshipName>Event_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Activity__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Activity__c/fields/Trailblazer_Event__c.field-meta.xml
<CustomField>
    <fullName>Trailblazer_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trailblazer Event</label>
    <referenceTo>Trailblazer_Event__c</referenceTo>
    <relationshipLabel>Event Activities</relationshipLabel>
    <relationshipName>Event_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Activity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vote</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Interaction</fullName>
            </value>
            <value>
                <fullName>Game 1</fullName>
            </value>
            <value>
                <fullName>Game 2</fullName>
            </value>
            <value>
                <fullName>Tweet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/Event_Attendees__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendees__c/fields/AttendeeExtId__c.field-meta.xml
<CustomField>
    <fullName>AttendeeExtId__c</fullName>
    <externalId>true</externalId>
    <label>AttendeeExtId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Checked_In__c.field-meta.xml
<CustomField>
    <fullName>Checked_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Checked In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email Address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Give_event_feedback__c.field-meta.xml
<CustomField>
    <fullName>Give_event_feedback__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Give event feedback</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Is_Speaker__c.field-meta.xml
<CustomField>
    <fullName>Is_Speaker__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Speaker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Is_Volunteer__c.field-meta.xml
<CustomField>
    <fullName>Is_Volunteer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Volunteer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Met_a_speaker__c.field-meta.xml
<CustomField>
    <fullName>Met_a_speaker__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Met a speaker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Met_a_volunteer__c.field-meta.xml
<CustomField>
    <fullName>Met_a_volunteer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Met a volunteer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Number_of_feedbacks_given__c.field-meta.xml
<CustomField>
    <fullName>Number_of_feedbacks_given__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of feedbacks given</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Number_of_people_met__c.field-meta.xml
<CustomField>
    <fullName>Number_of_people_met__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of people met</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Number_of_sessions_attended__c.field-meta.xml
<CustomField>
    <fullName>Number_of_sessions_attended__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of sessions attended</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Play_a_game__c.field-meta.xml
<CustomField>
    <fullName>Play_a_game__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Play a game</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Pre_Registered__c.field-meta.xml
<CustomField>
    <fullName>Pre_Registered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pre-Registered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Team_Name__c.field-meta.xml
<CustomField>
    <fullName>Team_Name__c</fullName>
    <label>Team Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Trailblazer_Event__c.field-meta.xml
<CustomField>
    <fullName>Trailblazer_Event__c</fullName>
    <label>Trailblazer Event</label>
    <referenceTo>Trailblazer_Event__c</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Tweet__c.field-meta.xml
<CustomField>
    <fullName>Tweet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tweet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Twitter_handle__c.field-meta.xml
<CustomField>
    <fullName>Twitter_handle__c</fullName>
    <label>Twitter handle</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <length>20</length>
    <label>Unique Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Updated_Twitter_Handle__c.field-meta.xml
<CustomField>
    <fullName>Updated_Twitter_Handle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updated Twitter Handle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Visited_a_Booth__c.field-meta.xml
<CustomField>
    <fullName>Visited_a_Booth__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visited a Booth</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Booth__c/Session_Booth__c.object-meta.xml
<CustomObject>
    <label>Session/Booth</label>
    <nameField>
        <label>Session/Booth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions/Booths</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Booth__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Booth__c/fields/Password_Used__c.field-meta.xml
<CustomField>
    <fullName>Password_Used__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Password Used</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Booth__c/fields/Trailblazer_Event__c.field-meta.xml
<CustomField>
    <fullName>Trailblazer_Event__c</fullName>
    <label>Trailblazer Event</label>
    <referenceTo>Trailblazer_Event__c</referenceTo>
    <relationshipName>Sessions_Booths</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Booth__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Session</fullName>
            </value>
            <value>
                <fullName>Booth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Booth_Attendance__c/Session_Booth_Attendance__c.object-meta.xml
<CustomObject>
    <label>Session/Booth Attendance</label>
    <nameField>
        <displayFormat>SBA-{0000}</displayFormat>
        <label>Session/Booth Attendance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session/Booth Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Booth_Attendance__c/fields/Event_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Event_Attendee__c</fullName>
    <label>Event Attendee</label>
    <referenceTo>Event_Attendees__c</referenceTo>
    <relationshipName>Session_Booth_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Booth_Attendance__c/fields/Session_Booth__c.field-meta.xml
<CustomField>
    <fullName>Session_Booth__c</fullName>
    <label>Session/Booth</label>
    <referenceTo>Session_Booth__c</referenceTo>
    <relationshipName>Session_Booth_Attendances</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trailblazer_Event__c/Trailblazer_Event__c.object-meta.xml
<CustomObject>
    <label>Trailblazer Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazer Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trailblazer_Event__c/fields/Check_In_Closed__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check In Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trailblazer_Event__c/fields/Event_Phase__c.field-meta.xml
<CustomField>
    <fullName>Event_Phase__c</fullName>
    <label>Event Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Check In</fullName>
            </value>
            <value>
                <fullName>Keynote 1</fullName>
            </value>
            <value>
                <fullName>Game 1</fullName>
            </value>
            <value>
                <fullName>Keynote 1 Feedback</fullName>
            </value>
            <value>
                <fullName>Booths and Sessions</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Game 2</fullName>
            </value>
            <value>
                <fullName>Keynote 2</fullName>
            </value>
            <value>
                <fullName>Keynote 2 Feedback</fullName>
            </value>
            <value>
                <fullName>Event Feedback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trailblazer_Event__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date of the event</description>
    <label>Start Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/EventAppCtrl.cls
public without sharing class EventAppCtrl {
    @AuraEnabled
    public static Trailblazer_Event__c getActiveEvent() {
        List<Trailblazer_Event__c> events = [
            SELECT Id, Check_In_Closed__c, Event_Phase__c, Name, Start_Date__c
            FROM Trailblazer_Event__c
            WHERE Active__c = TRUE
        ];
        if (!events.isEmpty()) {
            return events[0];
        }
        return null;
    }

    @AuraEnabled
    public static String getAttendeeByEmail(String email, String eventId) {
        Map<String, Object> result = new Map<String, Object>();
        List<Event_Attendees__c> attendees = [
            SELECT Id, Name, AttendeeExtId__c, Checked_In__c, Pre_Registered__c
            FROM Event_Attendees__c
            WHERE Email_Address__c = :email AND Trailblazer_Event__c = :eventId
        ];
        Trailblazer_Event__c event = [
            SELECT Id, Check_In_Closed__c
            FROM Trailblazer_Event__c
            WHERE Id = :eventId
        ];
        result.put('checkInClosed', event.Check_In_Closed__c);
        if (!attendees.isEmpty()) {
            result.put('attendeeId', attendees[0].Id);
            result.put('alreadyCheckedIn', attendees[0].Checked_In__c);
        }
        return JSON.serialize(result);
    }

    @AuraEnabled
    public static Event_Attendees__c getAttendeeById(String attendeeId) {
        Trailblazer_Event__c de = getActiveEvent();
        if (de != null) {
            List<Event_Attendees__c> attendees = [
                SELECT
                    Id,
                    Name,
                    Unique_Key__c,
                    Team_Name__c,
                    AttendeeExtId__c,
                    Pre_Registered__c
                FROM Event_Attendees__c
                WHERE Id = :attendeeId AND Trailblazer_Event__c = :de.Id
            ];
            if (!attendees.isEmpty()) {
                return attendees[0];
            }
        }
        return null;
    }

    @AuraEnabled
    public static Boolean updateAttendee(
        String attendeeId,
        String twitterHandle,
        String skills,
        Boolean fromQuest
    ) {
        try {
            Event_Attendees__c attendee = new Event_Attendees__c(
                Id = attendeeId
            );
            if (!String.isBlank(twitterHandle)) {
                attendee.Twitter_handle__c = twitterHandle;
            }
            if (!String.isBlank(skills)) {
                attendee.Skills__c = skills;
                attendee.Checked_In__c = true;
            }
            if (fromQuest == true) {
                attendee.Updated_Twitter_Handle__c = true;
            }
            update attendee;
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    @AuraEnabled
    public static Boolean saveActivity(
        String eventId,
        String attendeeId,
        String activityType,
        String activitySubType,
        String value,
        String additionalInfo
    ) {
        try {
            Event_Activity__c ea = new Event_Activity__c();
            ea.Trailblazer_Event__c = eventId;
            ea.Event_Attendee__c = attendeeId;
            ea.Type__c = activityType;
            ea.Sub_Type__c = activitySubType;
            ea.Value__c = value;
            ea.Additional_Info__c = additionalInfo;
            insert ea;
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    @AuraEnabled
    public static Event_Attendees__c getQuestMetrics(String attendeeId) {
        try {
            return [
                SELECT
                    Id,
                    Visited_a_Booth__c,
                    Number_of_sessions_attended__c,
                    Number_of_feedbacks_given__c,
                    Number_of_people_met__c,
                    Met_a_speaker__c,
                    Met_a_volunteer__c,
                    Give_event_feedback__c,
                    Play_a_game__c,
                    Tweet__c,
                    Twitter_handle__c,
                    Updated_Twitter_Handle__c
                FROM Event_Attendees__c
                WHERE Id = :attendeeId
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static CustomResponse isSecretValid(
        String secret,
        String eventId,
        String attendeeId
    ) {
        try {
            CustomResponse cr = new CustomResponse();
            List<Event_Attendees__c> attendees = [
                SELECT Id, Is_Speaker__c, Is_Volunteer__c
                FROM Event_Attendees__c
                WHERE
                    Unique_Key__c = :secret
                    AND Trailblazer_Event__c = :eventId
                    AND Checked_In__c = TRUE
                    AND Id != :attendeeId
            ];
            if (attendees.size() >= 1) {
                List<Event_Activity__c> allActivities = [
                    SELECT Id
                    FROM Event_Activity__c
                    WHERE
                        Event_Attendee__c = :attendeeId
                        AND Value__c = :secret
                        AND Type__c = 'Interaction'
                ];
                if (allActivities.size() == 0) {
                    // Insert event activity
                    String attendeeType;
                    if (attendees[0].Is_Speaker__c == true) {
                        attendeeType = 'Speaker';
                    } else if (attendees[0].Is_Volunteer__c == true) {
                        attendeeType = 'Volunteer';
                    }
                    Boolean saved = saveActivity(
                        eventId,
                        attendeeId,
                        'Interaction',
                        null,
                        secret,
                        attendeeType
                    );
                    if (saved == true) {
                        cr.isSuccess = true;
                    } else {
                        cr.isSuccess = false;
                        cr.message = 'Unable to save interaction. Please contact event staff.';
                    }
                } else {
                    // return interaction already addded
                    cr.isSuccess = false;
                    cr.message = 'An interaction with this person is already added.';
                }
            } else {
                cr.isSuccess = false;
                cr.message = 'Invalid code scanned, or this person has not checked in to the event.';
            }
            return cr;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public static void syncMetrics(Set<Id> attendeeIds) {
        Map<Id, List<Event_Activity__c>> attendeeActivityMap = new Map<Id, List<Event_Activity__c>>();
        Map<Id, List<Session_Booth_Attendance__c>> attendeeAttendanceMap = new Map<Id, List<Session_Booth_Attendance__c>>();

        List<Event_Activity__c> allActivities = [
            SELECT
                Event_Attendee__c,
                Sub_Type__c,
                Type__c,
                Value__c,
                Additional_Info__c
            FROM Event_Activity__c
            WHERE Event_Attendee__c IN :attendeeIds
        ];
        for (Event_Activity__c ea : allActivities) {
            List<Event_Activity__c> acts = attendeeActivityMap.get(
                ea.Event_Attendee__c
            );
            if (acts == null) {
                acts = new List<Event_Activity__c>();
            }
            acts.add(ea);
            attendeeActivityMap.put(ea.Event_Attendee__c, acts);
        }

        List<Session_Booth_Attendance__c> allAttendance = [
            SELECT Id, Event_Attendee__c, Session_Booth__r.Type__c
            FROM Session_Booth_Attendance__c
            WHERE Event_Attendee__c IN :attendeeIds
        ];
        for (Session_Booth_Attendance__c sb : allAttendance) {
            List<Session_Booth_Attendance__c> acts = attendeeAttendanceMap.get(
                sb.Event_Attendee__c
            );
            if (acts == null) {
                acts = new List<Session_Booth_Attendance__c>();
            }
            acts.add(sb);
            attendeeAttendanceMap.put(sb.Event_Attendee__c, acts);
        }

        List<Event_Attendees__c> attendeesToUpdate = new List<Event_Attendees__c>();
        for (Id attendeeId : attendeeActivityMap.keySet()) {
            Boolean visitedBooth = false;
            Integer sessionsAttended = 0;
            Integer feedbackGiven = 0;
            Integer peopleInteracted = 0;
            Boolean metVolunteer = false;
            Boolean metSpeaker = false;
            Boolean finishedGame = false;
            Boolean gaveEventFeedback = false;

            List<Event_Activity__c> acts = attendeeActivityMap.get(attendeeId);
            if (acts != null) {
                for (Event_Activity__c act : acts) {
                    if (
                        act.Type__c == 'Vote' &&
                        act.Sub_Type__c?.startsWith('session_feedback')
                    ) {
                        feedbackGiven++;
                    }
                    if (
                        act.Type__c == 'Vote' &&
                        act.Sub_Type__c == 'eventFeedback'
                    ) {
                        gaveEventFeedback = true;
                    }
                    if (act.Type__c == 'Game 1' || act.Type__c == 'Game 2') {
                        finishedGame = true;
                    }
                    if (act.Type__c == 'Interaction') {
                        peopleInteracted++;
                        if (act.Additional_Info__c == 'Speaker') {
                            metSpeaker = true;
                        }
                        if (act.Additional_Info__c == 'Volunteer') {
                            metVolunteer = true;
                        }
                    }
                }
            }

            List<Session_Booth_Attendance__c> atts = attendeeAttendanceMap.get(
                attendeeId
            );
            if (atts != null) {
                for (Session_Booth_Attendance__c sba : atts) {
                    if (sba.Session_Booth__r.Type__c == 'Session') {
                        sessionsAttended++;
                    }
                    if (sba.Session_Booth__r.Type__c == 'Booth') {
                        visitedBooth = true;
                    }
                }
            }

            attendeesToUpdate.add(
                new Event_Attendees__c(
                    Id = attendeeId,
                    Visited_a_Booth__c = visitedBooth,
                    Number_of_sessions_attended__c = sessionsAttended,
                    Number_of_feedbacks_given__c = feedbackGiven,
                    Number_of_people_met__c = peopleInteracted,
                    Give_event_feedback__c = gaveEventFeedback,
                    Play_a_game__c = finishedGame,
                    Met_a_speaker__c = metSpeaker,
                    Met_a_volunteer__c = metVolunteer
                )
            );
        }
        update attendeesToUpdate;
    }

    @AuraEnabled
    public static String getFeedbackMetrics(
        String eventId,
        String feedbackType
    ) {
        List<Event_Activity__c> ideas = [
            SELECT Id, Sub_Type__c, Value__c
            FROM Event_Activity__c
            WHERE
                Trailblazer_Event__c = :eventId
                AND Sub_Type__c = :feedbackType
                AND Type__c = 'Vote'
        ];
        Decimal total = 0;
        Decimal count = 0;
        List<Map<String, Object>> feedbackComments = new List<Map<String, Object>>();
        Integer mapIndex = 0;
        for (Event_Activity__c ea : ideas) {
            if (ea.Value__c != null) {
                Map<String, Object> m = (Map<String, Object>) JSON.deserializeUntyped(
                    ea.Value__c
                );
                total += Integer.valueOf(m.values()[0]);
                if (m.values().size() == 2) {
                    String feedback = String.valueOf(m.values()[1]);
                    if (feedback != null && feedback.length() > 0) {
                        Map<String, Object> tmpObj = new Map<String, Object>();
                        tmpObj.put('id', mapIndex);
                        tmpObj.put('feedback', feedback);
                        feedbackComments.add(tmpObj);
                        mapIndex++;
                    }
                }
                count++;
            }
        }
        Map<String, Object> results = new Map<String, Object>();
        results.put('count', count);
        results.put('score', count > 0 ? total.divide(count, 2) : 0);
        results.put('comments', feedbackComments);
        return JSON.serialize(results);
    }

    public static String randomString() {
        String[] validChars = new List<string>{
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'G',
            'H',
            'J',
            'K',
            'L',
            'M',
            'N',
            'P',
            'Q',
            'R',
            'S',
            'T',
            'U',
            'V',
            'W',
            'X',
            'Y',
            'Z',
            '1',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9'
        };
        String uniqueString = '';
        Integer validCharsLength = validChars.size();
        for (Integer i = 0; i < 5; i++) {
            uniqueString =
                uniqueString +
                validChars[(Integer) (Math.random() * validCharsLength)];
        }
        return uniqueString;
    }

    @AuraEnabled
    public static String saveSessionBoothAttendance(
        String sessionCode,
        String attendeeId,
        String eventId
    ) {
        CustomResponse cr = new CustomResponse();
        try {
            List<Session_Booth__c> sessionsAndBooths = [
                SELECT Id
                FROM Session_Booth__c
                WHERE Code__c = :sessionCode AND Trailblazer_Event__c = :eventId
                LIMIT 1
            ];
            if (sessionsAndBooths.size() == 1) {
                List<Session_Booth_Attendance__c> sbaList = [
                    SELECT Id
                    FROM Session_Booth_Attendance__c
                    WHERE
                        Event_Attendee__c = :attendeeId
                        AND Session_Booth__c = :sessionsAndBooths[0].Id
                ];
                if (sbaList.size() == 0) {
                    cr.isSuccess = true;
                    Session_Booth_Attendance__c sba = new Session_Booth_Attendance__c();
                    sba.Event_Attendee__c = attendeeId;
                    sba.Session_Booth__c = sessionsAndBooths[0].Id;
                    insert sba;
                    cr.message = sessionsAndBooths[0].Id;
                } else {
                    cr.isSuccess = true;
                    cr.message = sessionsAndBooths[0].Id;
                }
            } else {
                cr.isSuccess = false;
                cr.message = 'This code is not valid.';
            }
        } catch (Exception e) {
            cr.isSuccess = false;
            cr.message = 'An error occurred. Please contact event staff.';
        }

        return JSON.serialize(cr);
    }

    @AuraEnabled
    public static void generateOTP(String recordId) {
        Integer otp = Math.round((Math.random() * (900000) + 100000));
        Session_Booth__c sb = new Session_Booth__c(Id = recordId);
        sb.Password__c = String.valueOf(otp);
        sb.Password_Used__c = false;
        update sb;
    }

    @AuraEnabled
    public static Session_Booth__c login(String sessCode, String otp) {
        Trailblazer_Event__c ev = getActiveEvent();
        List<Session_Booth__c> sb = [
            SELECT Id, Name, Password__c, Password_Used__c
            FROM Session_Booth__c
            WHERE Code__c = :sessCode AND Trailblazer_Event__c = :ev.Id
            LIMIT 1
        ];
        if (sb.size() == 1) {
            if (sb[0].Password__c == otp && sb[0].Password_Used__c == false) {
                sb[0].Password_Used__c = true;
                update sb;
                return sb[0];
            }
        }
        return null;
    }

    @AuraEnabled(cacheable=true)
    public static List<Session_Booth_Attendance__c> getAttendeesForSessionOrBooth(
        String sessionOrBoothId
    ) {
        try {
            if (sessionOrBoothId != null) {
                return [
                    SELECT Id, Event_Attendee__r.Name
                    FROM Session_Booth_Attendance__c
                    WHERE Session_Booth__c = :sessionOrBoothId
                    ORDER BY CreatedDate DESC
                    LIMIT 10
                ];
            }
            return null;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void addAttendance(
        String sessionOrBoothId,
        String attendeeCode
    ) {
        try {
            List<Event_Attendees__c> attendees = [
                SELECT Id
                FROM Event_Attendees__c
                WHERE Unique_Key__c = :attendeeCode AND Checked_In__c = TRUE
            ];
            if (attendees.size() > 0) {
                List<Session_Booth_Attendance__c> sbaList = [
                    SELECT Id
                    FROM Session_Booth_Attendance__c
                    WHERE
                        Event_Attendee__c = :attendees[0].Id
                        AND Session_Booth__c = :sessionOrBoothId
                ];
                if (sbaList.size() == 0) {
                    Session_Booth_Attendance__c sba = new Session_Booth_Attendance__c();
                    sba.Event_Attendee__c = attendees[0].Id;
                    sba.Session_Booth__c = sessionOrBoothId;
                    insert sba;
                } else {
                    throw new AuraHandledException('Duplicate Entry');
                }
            } else {
                throw new AuraHandledException('Invalid code');
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Event_Attendees__c checkInPerson(String attendeeCode) {
        try {
            List<Event_Attendees__c> attendees = [
                SELECT Id, Name
                FROM Event_Attendees__c
                WHERE Unique_Key__c = :attendeeCode AND Checked_In__c = TRUE
            ];
            if (attendees.size() > 0) {
                update attendees;
                return attendees[0];
            } else {
                throw new AuraHandledException('Invalid code');
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Session_Booth__c> getSessionsAndBoothsForEvent(
        String eventId
    ) {
        return [
            SELECT Id, Name
            FROM Session_Booth__c
            WHERE Trailblazer_Event__c = :eventId
        ];
    }

    @AuraEnabled
    public static string getSurveyResults(String eventId) {
        try {
            List<Event_Activity__c> ideas = [
                SELECT Id, Sub_Type__c, Value__c
                FROM Event_Activity__c
                WHERE
                    Trailblazer_Event__c = :eventId
                    AND Sub_Type__c = 'survey'
                    AND Type__c = 'Vote'
            ];

            Map<String, Integer> updatesCounts = new Map<String, Integer>();
            Map<String, Integer> timeframeCounts = new Map<String, Integer>();
            Map<String, Integer> preferedPlaceCounts = new Map<String, Integer>();
            List<Map<String, Object>> feedbackComments = new List<Map<String, Object>>();

            Integer mapIndex = 0;

            for (Event_Activity__c ea : ideas) {
                if (ea.Value__c != null) {
                    SurveyResponse sr = (SurveyResponse) JSON.deserialize(
                        ea.Value__c,
                        SurveyResponse.class
                    );
                    List<String> tmpValues = sr.updates;
                    for (String s : tmpValues) {
                        Integer i = updatesCounts.get(s);
                        if (i == null) {
                            i = 0;
                        }
                        i++;
                        updatesCounts.put(s, i);
                    }

                    tmpValues = sr.timeframe;
                    for (String s : tmpValues) {
                        Integer i = timeframeCounts.get(s);
                        if (i == null) {
                            i = 0;
                        }
                        i++;
                        timeframeCounts.put(s, i);
                    }

                    tmpValues = sr.preferedPlace;
                    for (String s : tmpValues) {
                        Integer i = preferedPlaceCounts.get(s);
                        if (i == null) {
                            i = 0;
                        }
                        i++;
                        preferedPlaceCounts.put(s, i);
                    }

                    if (sr.notes != null && sr.notes.length() > 0) {
                        Map<String, Object> tmpObj = new Map<String, Object>();
                        tmpObj.put('id', mapIndex);
                        tmpObj.put('feedback', sr.notes);
                        feedbackComments.add(tmpObj);
                        mapIndex++;
                    }
                }
            }

            Map<String, Object> results = new Map<String, Object>();
            results.put('count', ideas.size());
            results.put('comments', feedbackComments);
            results.put('updatesCounts', updatesCounts);
            results.put('timeframeCounts', timeframeCounts);
            results.put('preferedPlaceCounts', preferedPlaceCounts);
            return JSON.serialize(results);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class SurveyResponse {
        public List<String> updates;
        public List<String> timeframe;
        public List<String> preferedPlace;
        public List<String> preferedLength;
        public String notes;
        public String otherValue;
    }

    public class CustomResponse {
        @AuraEnabled
        public Boolean isSuccess;
        @AuraEnabled
        public String message;
    }

    @AuraEnabled
    public static List<EventNameWithIdResponse> getEventNamesWithIds(){
        try {
            List<Trailblazer_Event__c> eventList = [SELECT Id, Name FROM Trailblazer_Event__c];
            List<EventNameWithIdResponse> responeList = new List<EventNameWithIdResponse>();
            for(Trailblazer_Event__c te : eventList) {
                EventNameWithIdResponse response = new EventNameWithIdResponse();
                response.label = te.Name;
                response.value = te.Id;
                responeList.add(response);
            }
            return responeList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class EventNameWithIdResponse {
        @AuraEnabled
        public String label;
        @AuraEnabled
        public String value;
    }
}