force-app/main/default/objects/Quiz__c/Quiz__c.object-meta.xml
<CustomObject>
    <label>Quiz</label>
    <nameField>
        <label>Quiz Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quizzes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Mark Quiz Active to organize and to show to end user.</description>
    <inlineHelpText>Mark Quiz Active to organize and to show to end user.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quiz__c/fields/Questions__c.field-meta.xml
<CustomField>
    <fullName>Questions__c</fullName>
    <description>All Questions with their response in a JSON format</description>
    <label>Questions</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quiz__c/fields/Quiz_Time__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Time__c</fullName>
    <description>overall quiz time in minutes.</description>
    <inlineHelpText>enter quiz time in minutes.</inlineHelpText>
    <label>Quiz Time</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quiz__c/fields/Trailblazer_Event__c.field-meta.xml
<CustomField>
    <fullName>Trailblazer_Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Trailblazer Event</label>
    <referenceTo>Trailblazer_Event__c</referenceTo>
    <relationshipLabel>Quizzes</relationshipLabel>
    <relationshipName>Quizzes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trailblazer_Event__c/Trailblazer_Event__c.object-meta.xml
<CustomObject>
    <label>Trailblazer Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazer Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EventQuizAppCtlr.cls
public with sharing class EventQuizAppCtlr {
    @AuraEnabled
    public static Quiz__c getActiveQuizEvent(String activeEventId){
        List<Quiz__c> quizList = new List<Quiz__c>([SELECT Quiz_Time__c, Questions__c FROM Quiz__c WHERE IsActive__c = true AND Trailblazer_Event__c =: activeEventId]);
        if(!quizList.isEmpty()){
            return quizList[0];
        }
        return null;
    }
}