force-app/main/default/objects/Event_Attendees__c/Event_Attendees__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendees__c/fields/Trailblazer_Event__c.field-meta.xml
<CustomField>
    <fullName>Trailblazer_Event__c</fullName>
    <label>Trailblazer Event</label>
    <referenceTo>Trailblazer_Event__c</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Tweet__c.field-meta.xml
<CustomField>
    <fullName>Tweet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tweet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Twitter_handle__c.field-meta.xml
<CustomField>
    <fullName>Twitter_handle__c</fullName>
    <label>Twitter handle</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trailblazer_Event__c/Trailblazer_Event__c.object-meta.xml
<CustomObject>
    <label>Trailblazer Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazer Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trailblazer_Event__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date of the event</description>
    <label>Start Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TwitterStreamQueuable.cls
public with sharing class TwitterStreamQueuable implements Queueable, Database.AllowsCallouts {
    public void execute(QueueableContext qc) {
        Trailblazer_Event__c de = EventAppCtrl.getActiveEvent();
        String dateFilter = de.Start_Date__c.formatGmt(
            'yyyy-MM-dd\'T\'HH:mm:ss\'Z\''
        );
        Set<String> usernames = makeCallout(null, dateFilter);

        List<Event_Attendees__c> attendees = [
            SELECT Id
            FROM Event_Attendees__c
            WHERE
                Twitter_handle__c IN :usernames
                AND Trailblazer_Event__c = :de.Id
        ];
        for (Event_Attendees__c da : attendees) {
            da.Tweet__c = true;
        }
        update attendees;

        // de.Last_Tweet_Sync__c = DateTime.now().addMinutes(-1);
        // update de;
    }

    public Set<String> makeCallout(String nextToken, String dateFilter) {
        String endpoint =
            'https://api.twitter.com/2/tweets/search/recent?query=' +
            EncodingUtil.urlDecode(Label.EventHashTag, 'UTF-8') +
            '&user.fields=id%2Cusername&max_results=100&tweet.fields=author_id&expansions=author_id';
        if (nextToken != null) {
            endpoint = endpoint + '&next_token=' + nextToken;
        }
        if (dateFilter != null) {
            endpoint =
                endpoint +
                '&start_time=' +
                EncodingUtil.urlEncode(dateFilter, 'UTF-8');
        }
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        req.setHeader('Authorization', 'Bearer <YOUR_TWITTER_TOKEN_HERE>');
        req.setEndpoint(endpoint);
        req.setMethod('GET');
        HttpResponse res = h.send(req);
        String body = res.getBody();
        system.debug(body);
        TwitterResponse tr = (TwitterResponse) JSON.deserialize(
            body,
            TwitterResponse.class
        );
        Set<String> usernames = new Set<String>();
        if (tr.includes?.users != null) {
            for (Users u : tr.includes.users) {
                usernames.add(u.username);
            }
        }
        if (tr.meta.next_token != null) {
            usernames.addAll(makeCallout(tr.meta.next_token, dateFilter));
        }
        return usernames;
    }

    public class Includes {
        public List<Users> users;
    }

    public class Meta {
        public String newest_id;
        public String oldest_id;
        public Integer result_count;
        public String next_token;
    }

    public class TwitterResponse {
        public List<Data> data;
        public Includes includes;
        public Meta meta;
    }

    public class Data {
        public String author_id;
        public String id;
        public String text;
    }

    public class Users {
        public String id;
        public String name;
        public String username;
    }
}