force-app/main/default/objects/Event_Attendees__c/Event_Attendees__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendees__c/fields/Trailblazer_Event__c.field-meta.xml
<CustomField>
    <fullName>Trailblazer_Event__c</fullName>
    <label>Trailblazer Event</label>
    <referenceTo>Trailblazer_Event__c</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <length>20</length>
    <label>Unique Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trailblazer_Event__c/Trailblazer_Event__c.object-meta.xml
<CustomObject>
    <label>Trailblazer Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazer Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EventAttendeeTriggerHandler.cls
public without sharing class EventAttendeeTriggerHandler {
    public static void generateRandomUniqueCode(
        List<Event_Attendees__c> eventAttendees
    ) {
        Set<Id> eventIds = new Set<Id>();
        for (Event_Attendees__c sb : eventAttendees) {
            eventIds.add(sb.Trailblazer_Event__c);
        }

        List<Event_Attendees__c> existingAttendees = [
            SELECT Id, Unique_Key__c, Trailblazer_Event__c
            FROM Event_Attendees__c
            WHERE Trailblazer_Event__c IN :eventIds
            LIMIT 50000
        ];

        Map<Id, List<String>> existingStrings = new Map<Id, List<String>>();
        for (Event_Attendees__c ea : existingAttendees) {
            List<String> tmpStrings = new List<String>();
            if (existingStrings.get(ea.Trailblazer_Event__c) != null) {
                tmpStrings = existingStrings.get(ea.Trailblazer_Event__c);
            }
            tmpStrings.add(ea.Unique_Key__c);
            existingStrings.put(ea.Trailblazer_Event__c, tmpStrings);
        }

        List<String> generatedRandomStrings = new List<String>();

        for (Event_Attendees__c ea : eventAttendees) {
            List<String> existingCodes = new List<String>();
            if (existingStrings.get(ea.Trailblazer_Event__c) != null) {
                existingCodes = existingStrings.get(ea.Trailblazer_Event__c);
            }
            String tmpRandom;
            do {
                tmpRandom = EventAppCtrl.randomString();
            } while (
                existingCodes.contains(tmpRandom) ||
                generatedRandomStrings.contains(tmpRandom)
            );

            ea.Unique_Key__c = tmpRandom;
            generatedRandomStrings.add(tmpRandom);
        }
    }
}